### ISSUE TITLE
Can't get it to work anymore; Protocol change?

### ISSUE THREAD

**Issue by misterbobdobalina** [gvsumasl/jacc#7]
The code stopped working by itself, has there been a protocol modification?

**Comment by eng-Robert** [comment]
It only works on the dev server. It is not working anymore on the deployment server.

**Comment by misterbobdobalina** [comment]
The original commect was for the "null" protocol change bug that I fixed some time ago.
Is there a new problem, since then?

**Comment by eng-Robert** [comment]
I updated (pulled) your changes and it worked well. Thanks.
I think you may close this issue to mark it as resolved.

How did you understand the protocol ? Is there any resource/document describing it ? Are you using special tools ?

**Comment by misterbobdobalina** [comment]
Bug due to not being able handle null value. It has been fixed.
